// Dummy skills data for testing
// Follows the SkillRecord type from type.d.ts

export const dummySkills = [
  {
    id: "1",
    title: "Write Code",
    slug: "write-code",
    description: "Learn to write efficient and clean code.",
    category: "Programming",
    tags: ["coding", "development", "software"],
    installCommand: "npm install write-code",
    createdAt: "2026-04-20T10:00:00Z",
    authorClerkId: "clerk_001",
    authorEmail: "author1@example.com",
  },
  {
    id: "2",
    title: "Debugging",
    slug: "debugging",
    description: "Master the art of debugging applications.",
    category: "Programming",
    tags: ["debug", "fix", "troubleshoot"],
    installCommand: "npm install debug-tool",
    createdAt: "2026-04-19T09:00:00Z",
    authorClerkId: "clerk_002",
    authorEmail: "author2@example.com",
  },
  {
    id: "3",
    title: "UI Design",
    slug: "ui-design",
    description: "Design beautiful and user-friendly interfaces.",
    category: "Design",
    tags: ["ui", "ux", "design"],
    installCommand: "npm install ui-designer",
    createdAt: "2026-04-18T08:00:00Z",
    authorClerkId: "clerk_003",
    authorEmail: "author3@example.com",
  },
  {
    id: "4",
    title: "API Integration",
    slug: "api-integration",
    description: "Integrate third-party APIs seamlessly.",
    category: "Backend",
    tags: ["api", "integration", "backend"],
    installCommand: "npm install api-integrator",
    createdAt: "2026-04-17T07:00:00Z",
    authorClerkId: "clerk_004",
    authorEmail: "author4@example.com",
  },
  {
    id: "5",
    title: "Testing",
    slug: "testing",
    description: "Write and run tests for your codebase.",
    category: "Quality Assurance",
    tags: ["test", "qa", "automation"],
    installCommand: "npm install test-suite",
    createdAt: "2026-04-16T06:00:00Z",
    authorClerkId: "clerk_005",
    authorEmail: "author5@example.com",
  },
];
